DATA_SEG SEGMENT
NUM1 DB 45H
ZEROS DB 0
ONES DB 0
DATA_SEG ENDS

CODE_SEG SEGMENT
ASSUME CS:CODE_SEG , DS:DATA_SEG
START : MOV AX,DATA_SEG ;INIT DATA SEGMENT
MOV DS,AX

MOV AL,NUM1 ;READ THE NUMBER
MOV CX,8 ;SET COUNTER TO 8

BACK:
ROR AL,1 ;ARS(ARTH LEFT SHIFT) BY 1 
JC CARRY1 ;IF CARRY FLAG = 1 GOTO CARRY1
INC ZEROS ;IF CARRY FLAG = 0 , INCREMENT ZEROS
JMP EXIT  ;UNCONDITIONAL JUMP TO EXIT
CARRY1 : ;LANDS HERE IF CARRY 1 IN BACK:
INC ONES ; increments ones

EXIT:
LOOP BACK ;LOOPS BACK TO BACK UNTILL CX=0

MOV AH,4CH ;exit to dos
INT 21H
CODE_SEG ENDS
END START

