DATA_SEG SEGMENT

NUM1 DW 22H
NUM2 DW 44H
CARRY DB 00H
SUM DW 0000H

DATA_SEG ENDS

CODE_SEG SEGMENT

ASSUME CS: CODE_SEG, DS: DATA_SEG
START:
MOV AX, DATA_SEG
MOV DS, AX ;INITIALISE THE DATA SEGMENT

MOV AX, NUM1 ;GET FIRST NUMBER
MOV BX, NUM2 ;GET SECOND NUMBER
ADD AL, BL ;ADD LOWER BYTES
DAA ;ADJUST SUM TO BCD
MOV DL,AL ;STORE LOWER BYTE SUM TO DL
MOV AL,AH ;MOVE HIGHER BYTE NUM1 TO AL
ADC AL,BH ;ADD HIGHER BYTES WITH CARRY...........here AL WAS TAKEN AGAIN BECAUSE DAA OP CAM ONLY BE PERFORMED ON AL
DAA ;ADJUST SUM TO BCD
MOV DH,AL ;STORE HIGHER BYTE SUM TO DH
MOV SUM,DX ;STORE THE RESULT

MOV AH, 4CH
INT 21H ;EXIT TO DOS
CODE_SEG ENDS
END START