DATA_SEG SEGMENT
ARY DB 'radar' ;LAST IS USALLY A NULL THEREFORE , DI MAI LEN-1 LENGE
LEN DW 05H
PALINDROME DB ?
DATA_SEG ENDS
CODE_SEG SEGMENT
ASSUME CS:CODE_SEG, DS:DATA_SEG
START:MOV AX,DATA_SEG
MOV DS ,AX ;INITIALIZE DATA SEGMENT

;DECLARING START AND END OF POINTERS
MOV SI,OFFSET ARY ;INITIALIZE THE POINTER TO START OF ARRAY/STRING
MOV DI,SI ;;INITIALIZE THE POINTER TO START OF ARRAY/STRING USING SL
MOV BX,LEN ;TAKES LEN OF ARRAY
DEC BX ;DEC THE LEN BY 1
ADD DI,BX ;INTIALIZE THE COUNTER TO THE DI+4 POSITION

AGAIN: ;START A LOOP CALLED AGAIN

MOV AL,[SI] ;READ THE FIRST ELEMENT
MOV BL,[DI] ;READ LAST ELEMENT
CMP AL,BL ;COMPARE THE CHARACTERS POINTED BY START AND END POINTERS

JNZ NOT_PALINDROME ;STRING NOT PALINDROME
INC SI
DEC DI
CMP SI,DI
JNZ AGAIN
MOV PALINDROME,09H
JMP EXIT

NOT_PALINDROME:
MOV PALINDROME,00H

EXIT:
MOV AH,4CH ;EXIT TO DOS
INT 21H
CODE_SEG ENDS
END START